# Generated by Django 3.1 on 2020-08-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('championId', models.CharField(default='', max_length=35, primary_key=True, serialize=False)),
                ('cost', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tftteamserver.champion')),
            ],
        ),
    ]
