# Generated by Django 3.1 on 2020-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tftteamserver', '0002_auto_20200818_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
