# Generated by Django 3.1 on 2020-08-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tftteamserver', '0003_champion_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='traits',
        ),
    ]
