# Generated by Django 3.1 on 2020-08-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tftteamserver', '0005_auto_20200818_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trait',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tftteamserver.champion'),
        ),
    ]
