# Generated by Django 3.1 on 2020-08-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tftteamserver', '0006_auto_20200818_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='traits',
        ),
    ]
