# Generated by Django 3.1 on 2020-08-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tftteamserver', '0007_remove_champion_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='champion',
        ),
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.ManyToManyField(related_name='traits', to='tftteamserver.Trait'),
        ),
    ]
